OPT = -g3 -O0
LIB_SOURCES1 = testmain.c error.c log.c string_intern.c icy_oop.c mem.c fileio.c shader_utils.c linmath.c icylang.c
LIB_SOURCES = $(addprefix src/, $(LIB_SOURCES1))
CC = gcc
TARGET = icy-test
LIB_OBJECTS =$(LIB_SOURCES:.c=.o)
LDFLAGS= -L. $(OPT) -Wextra -rdynamic -Wl,-rpath=.
LIBS= -licydb -lm -lglfw -lGL -lGLEW
ALL= $(TARGET)
CFLAGS =  -Isrc -Iinclude -std=gnu11 -gdwarf-2 -c $(OPT) -Wall -Wextra -Werror=implicit-function-declaration -Wformat=0 -D_GNU_SOURCE -fdiagnostics-color -Wextra  -Wwrite-strings -Werror -msse4.2 -mtune=corei7
 -Werror=maybe-uninitialized # -Wsuggest-attribute=const #-DDEBUG  

$(TARGET): $(LIB_OBJECTS)
	$(CC) $(LDFLAGS) $(LIB_OBJECTS) $(LIBS) -o $@

all:  $(ALL)

.c.o: $(HEADERS)
	$(CC) $(CFLAGS) $< -o $@ -MMD -MF $@.depends 
depend: h-depend
clean:
	rm -f $(LIB_OBJECTS) $(ALL) src/*.o.depends

-include $(LIB_OBJECTS:.o=.o.depends)
