// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _control_set{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const icy_control * k1, const icy_control * k2);
  const size_t sizes[1];

  icy_control * key;
  icy_mem * key_area;
}control_set;

control_set * control_set_create(const char * optional_name);
void control_set_set(control_set * table, icy_control key);
void control_set_insert(control_set * table, icy_control * key, size_t count);
void control_set_lookup(control_set * table, icy_control * keys, size_t * out_indexes, size_t count);
void control_set_remove(control_set * table, icy_control * keys, size_t key_count);
void control_set_clear(control_set * table);
void control_set_unset(control_set * table, icy_control key);
bool control_set_try_get(control_set * table, icy_control * key);
void control_set_print(control_set * table);
size_t control_set_iter(control_set * table, icy_control * keys, size_t keycnt, icy_control * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
