// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _function_type_set{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const function_type * k1, const function_type * k2);
  const size_t sizes[1];

  function_type * key;
  icy_mem * key_area;
}function_type_set;

function_type_set * function_type_set_create(const char * optional_name);
void function_type_set_set(function_type_set * table, function_type key);
void function_type_set_insert(function_type_set * table, function_type * key, size_t count);
void function_type_set_lookup(function_type_set * table, function_type * keys, size_t * out_indexes, size_t count);
void function_type_set_remove(function_type_set * table, function_type * keys, size_t key_count);
void function_type_set_clear(function_type_set * table);
void function_type_set_unset(function_type_set * table, function_type key);
bool function_type_set_try_get(function_type_set * table, function_type * key);
void function_type_set_print(function_type_set * table);
size_t function_type_set_iter(function_type_set * table, function_type * keys, size_t keycnt, function_type * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
