// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _void_to_control{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const void* * k1, const void* * k2);
  const size_t sizes[2];

  void* * key;
  icy_control * value;
  icy_mem * key_area;
  icy_mem * value_area;
}void_to_control;

void_to_control * void_to_control_create(const char * optional_name);
void void_to_control_set(void_to_control * table, void* key, icy_control value);
void void_to_control_insert(void_to_control * table, void* * key, icy_control * value, size_t count);
void void_to_control_lookup(void_to_control * table, void* * keys, size_t * out_indexes, size_t count);
void void_to_control_remove(void_to_control * table, void* * keys, size_t key_count);
void void_to_control_clear(void_to_control * table);
void void_to_control_unset(void_to_control * table, void* key);
bool void_to_control_try_get(void_to_control * table, void* * key, icy_control * value);
void void_to_control_print(void_to_control * table);
size_t void_to_control_iter(void_to_control * table, void* * keys, size_t keycnt, void* * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
