// This file is auto generated by table_compiler
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


window_state * window_state_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key", (char *)"width", (char *)"height", (char *)"x", (char *)"y"};
  static const char * const column_types[] = {"icy_control", "int", "int", "int", "int"};
  window_state * instance = calloc(sizeof(window_state), 1);
  icy_table_init((icy_table * )instance, optional_name, 5, (unsigned int[]){sizeof(icy_control), sizeof(int), sizeof(int), sizeof(int), sizeof(int)}, (char *[]){(char *)"key", (char *)"width", (char *)"height", (char *)"x", (char *)"y"});
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  return instance;
}

void window_state_insert(window_state * table, icy_control * key, int * width, int * height, int * x, int * y, size_t count){
  void * array[] = {(void* )key, (void* )width, (void* )height, (void* )x, (void* )y};
  icy_table_inserts((icy_table *) table, array, count);
}

void window_state_set(window_state * table, icy_control key, int width, int height, int x, int y){
  void * array[] = {(void* )&key, (void* )&width, (void* )&height, (void* )&x, (void* )&y};
  icy_table_inserts((icy_table *) table, array, 1);
}

void window_state_lookup(window_state * table, icy_control * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void window_state_remove(window_state * table, icy_control * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void window_state_clear(window_state * table){
  icy_table_clear((icy_table *) table);
}

void window_state_unset(window_state * table, icy_control key){
  window_state_remove(table, &key, 1);
}

bool window_state_try_get(window_state * table, icy_control * key, int * width, int * height, int * x, int * y){
  void * array[] = {(void* )key, (void* )width, (void* )height, (void* )x, (void* )y};
  void * column_pointers[] = {(void *)table->key, (void *)table->width, (void *)table->height, (void *)table->x, (void *)table->y};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(icy_control), sizeof(int), sizeof(int), sizeof(int), sizeof(int)};
  for(int i = 1; i < 5; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void window_state_print(window_state * table){
  icy_table_print((icy_table *) table);
}

size_t window_state_iter(window_state * table, icy_control * keys, size_t keycnt, icy_control * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
